name: Daily data refresh (no deploy)

on:
  schedule:
    - cron: "0 17 * * *"   # 00:00 WIB (UTC+7)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # ✅ Auto-install R packages listed below
      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            tidyverse
            lubridate
            readr
            here

      - name: Prepare data-updates branch
        run: |
          git fetch origin data-updates || true
          if git show-ref --verify --quiet refs/remotes/origin/data-updates; then
            git switch -c data-updates origin/data-updates
          else
            git switch -c data-updates
          fi

      - name: Prepare raw folder (placeholder)
        run: mkdir -p data/raw

      - name: Build driver_trips.csv via R
        run: Rscript scripts/build_driver_trips.R

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if ! git diff --quiet --exit-code -- data/driver_trips.csv; then
            git add data/driver_trips.csv
            git commit -m "data: update driver_trips.csv [skip deploy]"
            git push origin HEAD:data-updates
          else
            echo "No data changes; nothing to commit."
          fi

