name: Daily data refresh (no deploy)

on:
  schedule:
    - cron: "0 17 * * *"   # 00:00 WIB (UTC+7) = 17:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Check out the repo, but work on the data-updates branch
      - name: Checkout data-updates branch (create if needed)
        uses: actions/checkout@v4
        with:
          ref: data-updates
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("tidyverse","lubridate","readr","here"))'

      # If you have a real data source, replace this step with curl/wget/API download
      - name: Prepare raw folder (placeholder)
        run: |
          mkdir -p data/raw
          # echo "Place or download raw files here" > data/raw/README.txt

      - name: Build driver_trips.csv via R
        run: Rscript scripts/build_driver_trips.R

      - name: Commit only if data changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if ! git diff --quiet --exit-code -- data/driver_trips.csv; then
            git add data/driver_trips.csv
            git commit -m "data: update driver_trips.csv [skip deploy]"
            git push origin HEAD:data-updates
          else
            echo "No data changes; nothing to commit."
          fi
